
const PHONETICS = {
  "(at) first hand": "/ˈfɝst ˈhænd/",
  "a great deal (of)": "/ə ˈɡreɪt ˈdil/",
  "absolutely": "/ˌæbsəˈlutli/",
  "accessory": "/æˈksɛsɚi/",
  "accident": "/ˈæksədənt/",
  "admit": "/əˈdmɪt/",
  "after all": "/ˈæftɚ ˈɔl/",
  "afterwards (name usually afterward)": "/ˈæftɚwɚdz/",
  "agency": "/ˈeɪdʒənsi/",
  "agricultural": "/ˌæɡrəˈkʌltʃɚəl/",
  "agriculture": "/ˈæɡrɪˌkʌltʃɚ/",
  "ambassador": "/æˈmbæsədɚ/",
  "analysis": "/əˈnæləsəs/",
  "apart from": "/əˈpɑrt ˈfrʌm/",
  "apologise (name also apologize)": "/əˈpɑləˌdʒaɪz/",
  "appoint": "/əˈpɔɪnt/",
  "archery": "/ˈɑrtʃɚi/",
  "argue": "/ˈɑrɡju/",
  "argument": "/ˈɑrɡjəmənt/",
  "as a matter of fact": "/ˈæz ə ˈmætɚ ˈʌv ˈfækt/",
  "as a result": "/ˈæz ə rɪˈzʌlt/",
  "aside": "/əˈsaɪd/",
  "aside from": "/əˈsaɪd ˈfrʌm/",
  "assist": "/əˈsɪst/",
  "astronaut": "/ˈæstrəˌnɑt/",
  "atlantic": "/əˈtlæntɪk/",
  "atmosphere": "/ˈætməˌsfɪr/",
  "attach": "/əˈtætʃ/",
  "autonomous": "/ɔˈtɑnəməs/",
  "bank of canton": "/ˈbæŋk ˈʌv ˈkæntən/",
  "bar": "/ˈbɑr/",
  "basis": "/ˈbeɪsəs/",
  "be about to do sth": "/ˈbi əˈbaʊt ˈtu ˈdu/",
  "be willing to do sth": "/ˈbi ˈwɪlɪŋ ˈtu ˈdu/",
  "belief": "/bɪˈlif/",
  "beneath": "/bɪˈniθ/",
  "bet": "/ˈbɛt/",
  "beyond": "/bɪˈɑnd/",
  "bite": "/ˈbaɪt/",
  "boot": "/ˈbut/",
  "branch": "/ˈbræntʃ/",
  "brief": "/ˈbrif/",
  "bring about": "/ˈbrɪŋ əˈbaʊt/",
  "broad": "/ˈbrɔd/",
  "by accident": "/ˈbaɪ ˈæksədənt/",
  "california": "/ˌkæləˈfɔrnjə/",
  "cantonese": "/ˌkæntəˈniz/",
  "carla": "/ˈkɑrlɑ/",
  "carnival": "/ˈkɑrnəvəl/",
  "carry on": "/ˈkæri ˈɑn/",
  "carry sb through sth": "/ˈkæri ˈθru/",
  "cart": "/ˈkɑrt/",
  "ceremony": "/ˈsɛrəˌmoʊni/",
  "chain": "/ˈtʃeɪn/",
  "chairman": "/ˈtʃɛrmən/",
  "challenger": "/ˈtʃæləndʒɚ/",
  "charm": "/ˈtʃɑrm/",
  "cheese": "/ˈtʃiz/",
  "china": "/ˈtʃaɪnə/",
  "chip": "/ˈtʃɪp/",
  "christmas carol": "/ˈkrɪsməs ˈkærəl/",
  "church": "/ˈtʃɝtʃ/",
  "claim": "/ˈkleɪm/",
  "clap": "/ˈklæp/",
  "clerk": "/ˈklɝk/",
  "climate": "/ˈklaɪmət/",
  "clinic": "/ˈklɪnɪk/",
  "closing": "/ˈkloʊzɪŋ/",
  "clothing": "/ˈkloʊðɪŋ/",
  "colleague": "/ˈkɑliɡ/",
  "collection": "/kəˈlɛkʃən/",
  "comic": "/ˈkɑmɪk/",
  "coming-of-age day": "/ˈkʌmɪŋ ˈʌv ˈeɪdʒ ˈdeɪ/",
  "commercial": "/kəˈmɝʃəl/",
  "complain": "/kəˈmpleɪn/",
  "congratulate": "/kəˈnɡrætʃəˌleɪt/",
  "congratulation": "/kəˌnɡrætʃəˈleɪʃən/",
  "construction": "/kəˈnstrʌkʃən/",
  "consulate": "/ˈkɑnsələt/",
  "contain": "/kəˈnteɪn/",
  "costume": "/kɑˈstum/",
  "court": "/ˈkɔrt/",
  "crop": "/ˈkrɑp/",
  "current": "/ˈkɝənt/",
  "dare": "/ˈdɛr/",
  "data": "/ˈdeɪtə/",
  "decade": "/dɛˈkeɪd/",
  "decorate": "/ˈdɛkɚˌeɪt/",
  "definitely": "/ˈdɛfənətli/",
  "desire": "/dɪˈzaɪɚ/",
  "despair": "/dɪˈspɛr/",
  "determine": "/dəˈtɝmən/",
  "determined": "/dɪˈtɝmənd/",
  "diagram": "/ˈdaɪəˌɡræm/",
  "dilemma": "/dɪˈlɛmə/",
  "dinosaur": "/ˈdaɪnəˌsɔr/",
  "disappointed": "/ˌdɪsəˈpɔɪntɪd/",
  "disappointment": "/ˌdɪsəˈpɔɪntmənt/",
  "disguise": "/dɪˈsɡaɪz/",
  "district": "/ˈdɪstrɪkt/",
  "diverse": "/daɪˈvɝs/",
  "diversity": "/dɪˈvɝsɪti/",
  "downstairs": "/ˈdaʊˈnstɛrz/",
  "downtown": "/ˈdaʊˈntaʊn/",
  "dress (sb) up": "/ˈdrɛs ˈʌp/",
  "duty": "/ˈduti/",
  "eagle": "/ˈiɡəl/",
  "earn": "/ˈɝn/",
  "earn a living": "/ˈɝn ə ˈlɪvɪŋ/",
  "elect": "/ɪˈlɛkt/",
  "election": "/ɪˈlɛkʃən/",
  "element": "/ˈɛləmənt/",
  "elsewhere": "/ˈɛˌlswɛr/",
  "energetic": "/ˌɛnɚˈdʒɛtɪk/",
  "entrust": "/ɛˈntrʌst/",
  "envelope": "/ˈɛnvəˌloʊp/",
  "escape": "/ɪˈskeɪp/",
  "ethnic": "/ˈɛθnɪk/",
  "eve": "/ˈiv/",
  "eventually": "/ɪˈvɛntʃəwəli/",
  "evil": "/ˈivəl/",
  "except for": "/ɪˈksɛpt ˈfɔr/",
  "export": "/ˈɛkspɔrt/",
  "extent": "/ɪˈkstɛnt/",
  "external": "/ɪˈkstɝnəl/",
  "fable": "/ˈfeɪbəl/",
  "facility": "/fəˈsɪlɪti/",
  "fade": "/ˈfeɪd/",
  "fade away": "/ˈfeɪd əˈweɪ/",
  "faint": "/ˈfeɪnt/",
  "faith": "/ˈfeɪθ/",
  "fancy": "/ˈfænsi/",
  "faraway": "/ˈfɑrəˈweɪ/",
  "fatal": "/ˈfeɪtəl/",
  "feature": "/ˈfitʃɚ/",
  "fee": "/ˈfi/",
  "figure": "/ˈfɪɡjɚ/",
  "figure out": "/ˈfɪɡjɚ ˈaʊt/",
  "financial": "/fəˈnænʃəl/",
  "firecracker": "/ˈfaɪɚˌkrækɚ/",
  "firework": "/ˈfaɪˌrwɝk/",
  "first aid": "/ˈfɝst ˈeɪd/",
  "flexible": "/ˈflɛksəbəl/",
  "float": "/ˈfloʊt/",
  "foam": "/ˈfoʊm/",
  "fold": "/ˈfoʊld/",
  "fortune": "/ˈfɔrtʃən/",
  "fortune cookie": "/ˈfɔrtʃən ˈkʊki/",
  "frank": "/ˈfræŋk/",
  "frontier": "/frəˈntɪr/",
  "frown": "/ˈfraʊn/",
  "gather": "/ˈɡæðɚ/",
  "giant": "/ˈdʒaɪənt/",
  "globe": "/ˈɡloʊb/",
  "go off": "/ˈɡoʊ ˈɔf/",
  "grace": "/ˈɡreɪs/",
  "graffiti": "/ɡrəˈfiti/",
  "grateful": "/ˈɡreɪtfəl/",
  "gratitude": "/ˈɡrætəˌtud/",
  "gravity": "/ˈɡrævəti/",
  "gumbo": "/ˈɡʌmboʊ/",
  "halloween": "/ˌhæləˈwin/",
  "harm": "/ˈhɑrm/",
  "harvest": "/ˈhɑrvəst/",
  "have sth in common": "/ˈhæv ɪn ˈkɑmən/",
  "head to": "/ˈhɛd ˈtu/",
  "henry adams": "/ˈhɛnri ˈædəmz/",
  "henry norman bethune": "/ˈhɛnri ˈnɔrmən bəˈθjun/",
  "herbal": "/ˈɝbəl/",
  "hesitate": "/ˈhɛzəˌteɪt/",
  "high-end": "/ˈhaɪ ˈɛnd/",
  "hire": "/ˈhaɪɚ/",
  "historical": "/hɪˈstɔrɪkəl/",
  "horrible": "/ˈhɔrəbəl/",
  "hug": "/ˈhʌɡ/",
  "ignore": "/ˌɪˈɡnɔr/",
  "illustrate": "/ˈɪləˌstreɪt/",
  "immigrant": "/ˈɪməɡrənt/",
  "import": "/ˌɪˈmpɔrt/",
  "in a ... manner": "/ɪn ə ˈmænɚ/",
  "in case": "/ɪn ˈkeɪs/",
  "in closing": "/ɪn ˈkloʊzɪŋ/",
  "in despair": "/ɪn dɪˈspɛr/",
  "in memory of": "/ɪn ˈmɛmɚi ˈʌv/",
  "in return": "/ɪn rɪˈtɝn/",
  "in spite of": "/ɪn ˈspaɪt ˈʌv/",
  "in tears": "/ɪn ˈtɛrz/",
  "in that case": "/ɪn ˈðæt ˈkeɪs/",
  "in the hope of doing sth": "/ɪn ðə ˈhoʊp ˈʌv ˈduɪŋ/",
  "income": "/ˈɪˌnkʌm/",
  "indeed": "/ˌɪˈndid/",
  "independent": "/ˌɪndɪˈpɛndənt/",
  "independently": "/ˌɪndɪˈpɛndəntli/",
  "indicate": "/ˈɪndəˌkeɪt/",
  "inner": "/ˈɪnɚ/",
  "inner mongolia autonomous region": "/ˈɪnɚ mɑˈŋɡoʊliə ɔˈtɑnəməs ˈridʒən/",
  "insurance": "/ˌɪˈnʃʊrəns/",
  "intelligent": "/ˌɪˈntɛlədʒənt/",
  "intention": "/ˌɪˈntɛntʃən/",
  "item": "/ˈaɪtəm/",
  "jade": "/ˈdʒeɪd/",
  "jade rabbit": "/ˈdʒeɪd ˈræbət/",
  "jazz": "/ˈdʒæz/",
  "jeans": "/ˈdʒinz/",
  "journal": "/ˈdʒɝnəl/",
  "journey to the west": "/ˈdʒɝni ˈtu ðə ˈwɛst/",
  "joy": "/ˈdʒɔɪ/",
  "joyful": "/ˈdʒɔɪfəl/",
  "judge": "/ˈdʒʌdʒ/",
  "jupiter": "/ˈdʒupətɚ/",
  "keen": "/ˈkin/",
  "kindergarten": "/ˈkɪndɚˌɡɑrtən/",
  "lack": "/ˈlæk/",
  "lantern": "/ˈlæntɚn/",
  "lap": "/ˈlæp/",
  "launch": "/ˈlɔntʃ/",
  "leap": "/ˈlip/",
  "limited": "/ˈlɪmətəd/",
  "limp": "/ˈlɪmp/",
  "lip": "/ˈlɪp/",
  "loan": "/ˈloʊn/",
  "lunar": "/ˈlunɚ/",
  "maintain": "/meɪˈnteɪn/",
  "majority": "/məˈdʒɔrəti/",
  "make a bet": "/ˈmeɪk ə ˈbɛt/",
  "make-up": "/ˈmeɪk ˈʌp/",
  "mankind": "/ˈmæˈnkaɪnd/",
  "manner": "/ˈmænɚ/",
  "maple": "/ˈmeɪpəl/",
  "march": "/ˈmɑrtʃ/",
  "marriage": "/ˈmɛrɪdʒ/",
  "mars": "/ˈmɑrz/",
  "mashed potatoes": "/ˈmæʃt pəˈteɪtoʊz/",
  "material": "/məˈtɪriəl/",
  "medium": "/ˈmidiəm/",
  "memory": "/ˈmɛmɚi/",
  "mental": "/ˈmɛntəl/",
  "merry": "/ˈmɛri/",
  "merry christmas!": "/ˈmɛri ˈkrɪsməs/",
  "mexico": "/ˈmɛksəˌkoʊ/",
  "microwave (also microwave oven)": "/ˈmaɪkrəˌweɪv/",
  "midnight": "/ˈmɪˌdnaɪt/",
  "might": "/ˈmaɪt/",
  "mild": "/ˈmaɪld/",
  "mining": "/ˈmaɪnɪŋ/",
  "minority": "/maɪˈnɔrəti/",
  "mission": "/ˈmɪʃən/",
  "module": "/ˈmɑdʒul/",
  "moment": "/ˈmoʊmənt/",
  "mongolian": "/mɑˈŋɡoʊliən/",
  "monitor": "/ˈmɑnətɚ/",
  "moral": "/ˈmɔrəl/",
  "moral dilemma": "/ˈmɔrəl dɪˈlɛmə/",
  "muscle": "/ˈmʌsəl/",
  "mushroom": "/ˈmʌʃrum/",
  "musical": "/ˈmjuzɪkəl/",
  "mystery": "/ˈmɪstɚi/",
  "nachos": "/ˈnɑˌtʃoʊz/",
  "napa valley": "/ˈnæpə ˈvæli/",
  "narration": "/nɛˈreɪʃən/",
  "narrator": "/ˈnɛreɪtɚ/",
  "nasa": "/ˈnæsə/",
  "neat": "/ˈnit/",
  "neil armstrong": "/ˈnil ˈɑˌrmstrɑŋ/",
  "normal": "/ˈnɔrməl/",
  "nowhere": "/ˈnoʊˌwɛr/",
  "obligation": "/ˌɑbləˈɡeɪʃən/",
  "occasion": "/əˈkeɪʒən/",
  "occur": "/əˈkɝ/",
  "odd": "/ˈɑd/",
  "oliver": "/ˈɑləvɚ/",
  "on board": "/ˈɑn ˈbɔrd/",
  "on duty": "/ˈɑn ˈduti/",
  "on the basis of": "/ˈɑn ðə ˈbeɪsəs ˈʌv/",
  "opera": "/ˈɑprə/",
  "operation": "/ˌɑpɚˈeɪʃən/",
  "option": "/ˈɑpʃən/",
  "orbit": "/ˈɔrbət/",
  "origin": "/ˈɔrədʒən/",
  "otherwise": "/ˈʌðɚˌwaɪz/",
  "ought to": "/ˈɔt ˈtu/",
  "oxygen": "/ˈɑksədʒən/",
  "pass away": "/ˈpæs əˈweɪ/",
  "passive": "/ˈpæsɪv/",
  "patience": "/ˈpeɪʃəns/",
  "pattern": "/ˈpætɚn/",
  "peking union medical college (pumc)": "/ˈpiˈkɪŋ ˈjunjən ˈmɛdəkəl ˈkɑlɪdʒ/",
  "per": "/ˈpɝ/",
  "percentage": "/pɚˈsɛntədʒ/",
  "permission": "/pɚˈmɪʃən/",
  "permit": "/pɚˈmɪt/",
  "physician": "/fəˈzɪʃən/",
  "pillow": "/ˈpɪloʊ/",
  "plastic": "/ˈplæstɪk/",
  "pleased": "/ˈplizd/",
  "plot": "/ˈplɑt/",
  "poetry": "/ˈpoʊətri/",
  "poison": "/ˈpɔɪzən/",
  "poisonous": "/ˈpɔɪzənəs/",
  "pole": "/ˈpoʊl/",
  "portia langham": "/ˈpɔrʃə ˈlæŋhæm/",
  "portsmouth square": "/ˈpɔrtsməθ ˈskwɛr/",
  "postpone": "/poʊˈstpoʊn/",
  "pot": "/ˈpɑt/",
  "precious": "/ˈprɛʃəs/",
  "pregnant": "/ˈprɛɡnənt/",
  "principle": "/ˈprɪnsəpəl/",
  "procedure": "/prəˈsidʒɚ/",
  "provide for sb": "/prəˈvaɪd ˈfɔr/",
  "publish": "/ˈpʌblɪʃ/",
  "pudding": "/ˈpʊdɪŋ/",
  "pumpkin": "/ˈpʌmpkɪn/",
  "pursue": "/pɚˈsu/",
  "range": "/ˈreɪndʒ/",
  "range from ... to ...": "/ˈreɪndʒ ˈfrʌm ˈtu/",
  "recycle": "/riˈsaɪkəl/",
  "reflect": "/rɪˈflɛkt/",
  "region": "/ˈridʒən/",
  "regular": "/ˈrɛɡjəlɚ/",
  "regularly": "/ˈrɛɡjəlɚli/",
  "reid": "/ˈrid/",
  "reject": "/rɪˈdʒɛkt/",
  "rejection": "/rɪˈdʒɛkʃən/",
  "religion": "/rɪˈlɪdʒən/",
  "religious": "/rɪˈlɪdʒəs/",
  "replace": "/ˌriˈpleɪs/",
  "represent": "/ˌrɛprɪˈzɛnt/",
  "resident physician": "/ˈrɛzɪdənt fəˈzɪʃən/",
  "resource": "/ˈrisɔrs/",
  "respect": "/rɪˈspɛkt/",
  "respond": "/rɪˈspɑnd/",
  "response": "/rɪˈspɑns/",
  "result in": "/rɪˈzʌlt ɪn/",
  "retire": "/rɪˈtaɪr/",
  "riddle": "/ˈrɪdəl/",
  "rio": "/ˈrioʊ/",
  "roast": "/ˈroʊst/",
  "roast turkey": "/ˈroʊst ˈtɝki/",
  "robe": "/ˈroʊb/",
  "robert louis stevenson": "/ˈrɑbɚt ˈluɪs ˈstivənsən/",
  "rocket": "/ˈrɑkət/",
  "roderick": "/ˈrɑdrɪk/",
  "run out": "/ˈrʌn ˈaʊt/",
  "sail": "/ˈseɪl/",
  "samba": "/ˈsɑmbə/",
  "san francisco": "/ˈsæn fræˈnsɪskoʊ/",
  "satellite": "/ˈsætəˌlaɪt/",
  "saving": "/ˈseɪvɪŋ/",
  "saying": "/ˈseɪɪŋ/",
  "scare": "/ˈskɛr/",
  "scared": "/ˈskɛrd/",
  "scene": "/ˈsin/",
  "scholarship": "/ˈskɑlɚˌʃɪp/",
  "seek": "/ˈsik/",
  "seek one’s fortune": "/ˈsik ˈwʌn ˈɛs ˈfɔrtʃən/",
  "select": "/səˈlɛkt/",
  "sequence": "/ˈsikwəns/",
  "series": "/ˈsɪriz/",
  "series of": "/ˈsɪriz ˈʌv/",
  "servant": "/ˈsɝvənt/",
  "set off": "/ˈsɛt ˈɔf/",
  "settle": "/ˈsɛtəl/",
  "shallow": "/ˈʃæloʊ/",
  "sharp": "/ˈʃɑrp/",
  "signal": "/ˈsɪɡnəl/",
  "significant": "/səˈɡnɪfɪkənt/",
  "smartphone": "/ˈsmɑˌrtfoʊn/",
  "so as to (do sth)": "/ˈsoʊ ˈæz ˈtu/",
  "soap": "/ˈsoʊp/",
  "solar": "/ˈsoʊlɚ/",
  "solar system": "/ˈsoʊlɚ ˈsɪstəm/",
  "sort": "/ˈsɔrt/",
  "souvenir": "/ˌsuvəˈnɪr/",
  "soyuz 11": "/ˈsɔɪəz/",
  "spacecraft": "/ˈspeɪˌskræft/",
  "spacewalk": "/ˈspeɪˌswɑk/",
  "spicy": "/ˈspaɪsi/",
  "spill": "/ˈspɪl/",
  "spot": "/ˈspɑt/",
  "sputnik 1": "/ˈspʌtnɪk/",
  "staff": "/ˈstæf/",
  "stair": "/ˈstɛr/",
  "sufficient": "/səˈfɪʃənt/",
  "suit": "/ˈsut/",
  "super": "/ˈsupɚ/",
  "tai chi": "/ˈtaɪ ˈkaɪ/",
  "tailor": "/ˈteɪlɚ/",
  "take advantage of": "/ˈteɪk æˈdvæntɪdʒ ˈʌv/",
  "take out a loan": "/ˈteɪk ˈaʊt ə ˈloʊn/",
  "tear": "/ˈtɛr/",
  "telescope": "/ˈtɛləˌskoʊp/",
  "tend": "/ˈtɛnd/",
  "tend to do sth": "/ˈtɛnd ˈtu ˈdu/",
  "tension": "/ˈtɛnʃən/",
  "tent": "/ˈtɛnt/",
  "thanksgiving (day)": "/ˌθæˈŋksɡɪvɪŋ/",
  "the golden gate bridge": "/ðə ˈɡoʊldən ˈɡeɪt ˈbrɪdʒ/",
  "the international space station": "/ðə ˌɪntɚˈnæʃənəl ˈspeɪs ˈsteɪʃən/",
  "the media": "/ðə ˈmidiə/",
  "the mission district": "/ðə ˈmɪʃən ˈdɪstrɪkt/",
  "the national people’s congress": "/ðə ˈnæʃənəl ˈpipəl ˈɛs ˈkɑŋɡrəs/",
  "the north/south pole": "/ðə ˈnɔrθ ˈsaʊθ ˈpoʊl/",
  "the people’s republic of china": "/ðə ˈpipəl ˈɛs riˈpʌblək ˈʌv ˈtʃaɪnə/",
  "the phantom of the opera": "/ðə ˈfæntəm ˈʌv ðə ˈɑprə/",
  "the richmond district": "/ðə ˈrɪtʃmənd ˈdɪstrɪkt/",
  "the upper class": "/ðə ˈʌpɚ ˈklæs/",
  "the ussr": "/ðə ˌjuˌɛˌsɛˈsɑr/",
  "therefore": "/ˈðɛˌrfɔr/",
  "tin how temple": "/ˈtɪn ˈhaʊ ˈtɛmpəl/",
  "tissue": "/ˈtɪˌsju/",
  "to ... extent": "/ˈtu ɪˈkstɛnt/",
  "to be frank": "/ˈtu ˈbi ˈfræŋk/",
  "to be honest": "/ˈtu ˈbi ˈɑnəst/",
  "to name but a few": "/ˈtu ˈbʌt ə ˈfju/",
  "todd": "/ˈtɑd/",
  "towel": "/ˈtaʊəl/",
  "transmit": "/træˈnzmɪt/",
  "trip over": "/ˈtrɪp ˈoʊvɚ/",
  "tuition": "/tjuˈɪʃən/",
  "tuition fees": "/tjuˈɪʃən ˈfiz/",
  "turkey": "/ˈtɝki/",
  "typical": "/ˈtɪpəkəl/",
  "union": "/ˈjunjən/",
  "universe": "/ˈjunəˌvɝs/",
  "upper": "/ˈʌpɚ/",
  "upper-class": "/ˈʌpɚ ˈklæs/",
  "vehicle": "/ˈvihɪkəl/",
  "virtue": "/ˈvɝtʃu/",
  "voyager 1": "/ˈvɔɪədʒɚ/",
  "waitress": "/ˈweɪtrəs/",
  "wedding": "/ˈwɛdɪŋ/",
  "whisper": "/ˈwɪspɚ/",
  "willing": "/ˈwɪlɪŋ/",
  "wrestle": "/ˈrɛsəl/",
  "wrestler": "/ˈrɛsəlɚ/",
  "wrestling": "/ˈrɛslɪŋ/",
  "yuri gagarin": "/ˈjʊri ɡəˈɡærən/"
};

